server:
  port: 7001
  servlet:
    context-path: /coupon-template

spring:
  application:
    name: eureka-client-coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/coupon_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Djangobbs
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8 # 最大池大小
      minimum-idle: 4 # 连接池中维护的最小空闲连接数
      idle-timeout: 30000 # 允许连接在连接池中空闲的最长时间
      connection-timeout: 30000 # 客户端等待连接池链接的最大毫秒
      max-lifetime: 45000 # 池中连接关闭后最长的生命周期
      auto-commit: true # 从池返回的连接的默认自动提交行为，默认为 true
      pool-name: CouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # password:
    # 连接超时时间
    timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

# ------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: coupon-template
    groupId: coupon-service
    artifactId: coupon-template
    version: 1.0-SNAPSHOT

# ------------------------------------------------------------------------------------------------------

logging:
  level:
    com.imooc.coupon: debug
